' one to many antara user dan order
@startuml
 class User {
    +id: int 
    +name: string 
    +email: string
    +password: string
 }

 class order{
    +id: int 
    +user_id: int
    +order_date:DateTime 
    +total_amount:Decimal
 }

 User "1".."0..*" Order : "One to Many"
 @enduml
